    language: python # => 1

    python: # => 2

      - "2.7"

    services: # => 3

      - sqlite3

    env: # => 4

      -DJANGO=1.8 DB=sqlite3
    install: # => 5

      - pip install -r requirements.txt

    before_script: # => 6

    script: # => 7

      - python manage.py test
